name: wfcvm-ucvm-ci

on:
  push:
    branches: [ foo ]

jobs:
  wfcvm-build-ucvm-mac:
    runs-on: macos-latest
    strategy:
      matrix:
        python-version: [3.7]
    steps:
    - name: set UCVM_SRC_PATH 
      run: echo "UCVM_SRC_PATH=$RUNNER_WORKSPACE/wfcvm/ucvm" >> $GITHUB_ENV
    - name: set UCVM_INSTALL_PATH 
      run: echo "UCVM_INSTALL_PATH=$RUNNER_WORKSPACE/wfcvm/target" >> $GITHUB_ENV
### build ucvm(main) first 
    - id: get-ucvm 
      uses: actions/checkout@v2
      with: 
        repository: 'SCECcode/UCVM'
        ref: main
        path: ucvm
    - id: build-ucvm
      uses: ./ucvm/.github/actions/build-ucvm-action
      with:
         initiating-repo: 'wfcvm'
         target-model: 'wfcvm'
         target-branch: 'testMei'
#    - name: Start SSH via Ngrok
#      if: ${{ failure() }}
#      uses: luchihoratiu/debug-via-ssh@main
#      with:
#            NGROK_AUTH_TOKEN: ${{ secrets.NGROK_TOKEN }}
#            NGROK_TIMEOUT: 3000
#            SSH_PASS: ${{ secrets.NGROK_SECRET }}
    - id: get-result
      run: more ${{ steps.build-ucvm.outputs.build-log }}
      shell: bash
    - name: move stock wfcvm away
      run: (rm -rf $RUNNER_WORKSPACE/wfcvm/ucvm/work/model/wfcvm)
      shell: bash
### build wfcvm from github 
    - name: checkout wfcvm main
      uses: actions/checkout@v2
      with: 
        ref: main
        path: wfcvm
    - name: move it to the right location
      run: (mv wfcvm $RUNNER_WORKSPACE/wfcvm/ucvm/work/model; pwd; ls)
      shell: bash
    - name: build wfcvm as part of ucvm 
      run: (cd $RUNNER_WORKSPACE/wfcvm/ucvm/work/model/wfcvm; ./.github/scripts/wfcvm-build.sh)
      shell: bash
### check ucvm is still valid
    - name: check on ucvm
      run: (source $UCVM_INSTALL_PATH/conf/ucvm_env.sh; ucvm_query -H)
      shell: bash
    - name: test wfcvm with ucvm
      run: (cd $RUNNER_WORKSPACE/wfcvm/ucvm/work/model/wfcvm; source $UCVM_INSTALL_PATH/conf/ucvm_env.sh; ./.github/scripts/wfcvm-test-ucvm.sh)
      shell: bash
#    - name: Start SSH via Ngrok
#      if: ${{ success() }}
#      uses: luchihoratiu/debug-via-ssh@main
#      with:
#            NGROK_AUTH_TOKEN: ${{ secrets.NGROK_TOKEN }}
#            NGROK_TIMEOUT: 3000
#            SSH_PASS: ${{ secrets.NGROK_SECRET }}
    - name: test wfcvm under ucvm
      run: (cd $RUNNER_WORKSPACE/wfcvm/ucvm; source $UCVM_INSTALL_PATH/conf/ucvm_env.sh; ./.github/scripts/ucvm-test.sh)
      shell: bash

  wfcvm-build-ucvm-linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7]
    steps:
    - name: set UCVM_SRC_PATH 
      run: echo "UCVM_SRC_PATH=$RUNNER_WORKSPACE/wfcvm/ucvm" >> $GITHUB_ENV
    - name: set UCVM_INSTALL_PATH 
      run: echo "UCVM_INSTALL_PATH=$RUNNER_WORKSPACE/wfcvm/target" >> $GITHUB_ENV
### build ucvm(main) first 
    - id: get-ucvm 
      uses: actions/checkout@v2
      with: 
        repository: 'SCECcode/UCVM'
        ref: main 
        path: ucvm
    - id: build-ucvm
      uses: ./ucvm/.github/actions/build-ucvm-action
      with:
         initiating-repo: 'wfcvm'
         target-model: 'wfcvm'
         target-branch: 'testMei'
    - id: get-result
      run: more ${{ steps.build-ucvm.outputs.build-log }}
      shell: bash
    - id: show-branch
      run: git log
      shell: bash
    - name: move stock wfcvm away
      run: (rm -rf $RUNNER_WORKSPACE/wfcvm/ucvm/work/model/wfcvm)
      shell: bash
### build wfcvm from github 
    - name: checkout wfcvm main
      uses: actions/checkout@v2
      with: 
        path: wfcvm
    - name: move it to the right location
      run: (mv wfcvm $RUNNER_WORKSPACE/wfcvm/ucvm/work/model; pwd; ls)
      shell: bash
    - name: build wfcvm as part of ucvm 
      run: (cd $RUNNER_WORKSPACE/wfcvm/ucvm/work/model/wfcvm; ./.github/scripts/wfcvm-build.sh)
      shell: bash
### check ucvm is still valid
    - name: check on ucvm
      run: (source $UCVM_INSTALL_PATH/conf/ucvm_env.sh; ucvm_query -H)
      shell: bash
    - name: test wfcvm with ucvm
      run: (cd $RUNNER_WORKSPACE/wfcvm/ucvm/work/model/wfcvm; source $UCVM_INSTALL_PATH/conf/ucvm_env.sh; ./.github/scripts/wfcvm-test-ucvm.sh)
      shell: bash
#   - name: Start SSH via Ngrok
#     if: ${{ success() }}
#     uses: luchihoratiu/debug-via-ssh@main
#     with:
#           NGROK_AUTH_TOKEN: ${{ secrets.NGROK_TOKEN }}
#           NGROK_TIMEOUT: 3000
#           SSH_PASS: ${{ secrets.NGROK_SECRET }}
    - name: test wfcvm under ucvm
      run: (cd $RUNNER_WORKSPACE/wfcvm/ucvm; source $UCVM_INSTALL_PATH/conf/ucvm_env.sh; ./.github/scripts/ucvm-test.sh)
      shell: bash



