name: wfcvm-ci

on:
  push:
    branches: [ main ]

jobs:
  wfcvm-build-standalone-mac:
    runs-on: macos-latest
    strategy:
      matrix:
        python-version: [3.7]
    steps:
    - name: set UCVM_SRC_PATH 
      run: echo "UCVM_SRC_PATH=$RUNNER_WORKSPACE/ucvm" >> $GITHUB_ENV
    - name: set UCVM_INSTALL_PATH 
      run: echo "UCVM_INSTALL_PATH=$RUNNER_WORKSPACE/target" >> $GITHUB_ENV
    - name: checkout wfcvm main
      uses: actions/checkout@v2
      with: 
        ref: main
    - name: check environment
      run: (echo $RUNNER_WORKSPACE; echo $UCVM_INSTALL_PATH)
    - name: build wfcvm 
      run: ./.github/scripts/wfcvm-build.sh 
      shell: bash
    - name: test wfcvm standalone
      run: ./.github/scripts/wfcvm-test-standalone.sh
      shell: bash
#     - name: Start SSH via Ngrok
#       if: ${{ failure() }}
#       uses: luchihoratiu/debug-via-ssh@main
#       with:
#             NGROK_AUTH_TOKEN: ${{ secrets.NGROK_TOKEN }}
#             NGROK_TIMEOUT: 3000
#             SSH_PASS: ${{ secrets.NGROK_SECRET }}

  wfcvm-build-standalone-linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7]
    steps:
    - name: set UCVM_SRC_PATH 
      run: echo "UCVM_SRC_PATH=$RUNNER_WORKSPACE/ucvm" >> $GITHUB_ENV
    - name: set UCVM_INSTALL_PATH 
      run: echo "UCVM_INSTALL_PATH=$RUNNER_WORKSPACE/target" >> $GITHUB_ENV
    - name: checkout wfcvm main
      uses: actions/checkout@v2
      with: 
        ref: main 
    - name: build wfcvm
      run: ./.github/scripts/wfcvm-build.sh
      shell: bash
    - name: test wfcvm standalone
      run: ./.github/scripts/wfcvm-test-standalone.sh
      shell: bash
#    - name: Start SSH via Ngrok
#      if: ${{ success() }}
#      uses: luchihoratiu/debug-via-ssh@main
#      with:
#            NGROK_AUTH_TOKEN: ${{ secrets.NGROK_TOKEN }}
#            NGROK_TIMEOUT: 3000
#            SSH_PASS: ${{ secrets.NGROK_SECRET }}

